### ISSUE TITLE
More flexibility in Impl::Configuration

### ISSUE THREAD

**Issue by ohler55** [ohler55/wabur#110]
The current Configuration only allows the base to be set which causes wabur to create a wabur director and write data into it. It would be better not to assume the base directory is where the data should be stored. Having an option to specify `--dir example/sample/wabur/data` in the sample start script would be better. Or maybe `--data.dir`

**Comment by ashmaroli** [comment]
`--base` doesn't define the directory to write data into. `config['data_dir']` does..
`--base` configures a directory path as the Seat of all action / the Capital / Headquarters or likewise..

IMO, limiting operations to single central directory allows greater security with lesser overhead. Otherwise we'd have to have system to check directory traversal attacks and the like..

**Comment by ohler55** [comment]
There really isn't an attach vector here since the person starting the app is on the machine running wabur and their permissions control what they can access.

We can see that for the example/sample the default directory is not the correct one since we are starting all examples from the wabur root.

**Comment by ohler55** [comment]
Addressed in PR #115
